myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', ProductList.as_view(), name='product-list'),
    path('product/<int:pk>/', ProductDetail.as_view(), name='product-detail'),
    path('product/create/', ProductCreate.as_view(), name='product-create'),
    # Shopping Cart URLs
    path('cart/', cart_detail, name='cart-detail'),
    path('cart/add/<int:pk>/', cart_add, name='cart-add'),
    path('cart/remove/<int:pk>/', cart_remove, name='cart-remove'),
    path('cart/update/<int:pk>/', cart_update, name='cart-update'),
]

shop/models.py
from django.db import models
from shop.forms import CartAddProductForm

class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f'Category {self.name}'

class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Tags'
    
    def __str__(self):
        return f'Tag {self.name}'

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Nombre del producto')
    description = models.TextField('Descripcion del producto')
    price = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    is_active = models.BooleanField(default=True, help_text='Si el producto está activo se mostrará en la página principal')
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='products', blank=True, null=True, help_text='La imagen debe de tener un máximo de 300x300')
    tag = models.ManyToManyField(Tag, related_name='products')

    def __str__(self):
        return self.name

    @property
    def category_name(self):
        return self.category.name

# Shopping Cart Models

class Cart(models.Model):
    pass

    class Meta:
        verbose_name = 'Shopping Cart'
        verbose_name_plural = 'Shopping Carts'
    
    def __str__(self):
        return f'Shopping Cart {self.id}'
    
    @property
    def total_items(self):
        return self.items.count()

    @property
    def total_price(self):
        return sum([item.total_price for item in self.items.all()])

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        verbose_name = 'Shopping Cart Item'
        verbose_name_plural = 'Shopping Cart Items'
    
    def __str__(self):
        return self.product.name
    
    @property
    def total_price(self):
        return self.product.price * self.quantity
    
    def get_form(self, data=None):
        initial = {'quantity': self.quantity}
        return CartAddProductForm(initial=initial)

shop/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=1)

shop/views.py
from typing import Any
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django import forms

from shop.models import *
from shop.utils import get_cart
from shop.forms import CartAddProductForm

'''def product_list(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)'''

class ProductList(ListView):
    model = Product
    template_name = 'shop/product/list.html'
    context_object_name = 'products'


'''def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'product': product
    }
    return render(request, 'shop/product/detail.html', context)'''

class ProductDetail(DetailView):
    model = Product
    template_name = 'shop/product/detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CartAddProductForm()
        return context


'''def product_create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        category = request.POST.get('category')
        category = Category.objects.get(id=category)
        product = Product.objects.create(
            name=name,
            description=description,
            price=price,
            category=category
        )
        return redirect('shop:product-detail', pk=product.id)

    context = {
        'categories': Category.objects.all()
    }
    return render(request, 'shop/product/form.html', context)'''

class ProductForm(forms.ModelForm):
    short_description = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'class': 'form-control'}), required=False)

    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category', 'image']
    
    def clean_name(self):
        name = self.cleaned_data['name']
        if Product.objects.filter(name=name).exists():
            raise forms.ValidationError('Product with this name already exists')
        return name


class ProductCreate(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'shop/product/form.html'
    success_url = '/'

# Shopping Cart Views

def cart_detail(request):
    cart = get_cart(request)
    context = {
        'cart': cart
    }
    return render(request, 'shop/cart/detail.html', context)

def cart_add(request, pk):
    product = get_object_or_404(Product, pk=pk)
    cart = get_cart(request)
    quantity = request.POST.get('quantity')
    cart_item, created = CartItem.objects.get_or_create(
        cart=cart,
        product=product,
        defaults={'quantity': quantity}
    )
    if not created:
        cart_item.quantity += int(quantity)
        cart_item.save()
    return redirect('shop:cart-detail')

def cart_remove(request, pk):
    cart_item = get_object_or_404(CartItem, pk=pk)
    cart_item.delete()
    return redirect('shop:cart-detail')

def cart_update(request, pk):
    cart_item = get_object_or_404(CartItem, pk=pk)
    quantity = request.POST.get('quantity')
    cart_item.quantity = quantity
    cart_item.save()
    return redirect('shop:cart-detail')

shop/templates/shop/base.html
<!doctype html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ product }}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        
        {% block content %}
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

shop/templates/shop/cart/detail.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Carrito de Compras</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        
        <div class="container py-5">
            <div class="card">
                <div class="card-body p-4">
                    <div class="row">
                        <div class="col">
                            <h5 class="mb-3">
                                <a href="{% url 'shop:product-list' %}" class="text-body">
                                    <i class="fas fa-long-arrow-alt-left me-2"></i>Continuar comprando
                                </a>
                            </h5>
                            <hr>
                            <div class="d-flex justify-content-between align-items-center mb-4">
                                <div>
                                    <p class="mb-1">Carrito de compras</p>
                                    <p class="mb-0">Tienes un total de {{ cart.total_items }} producto{{ cart.total_items|pluralize }} en tu carrito</p>
                                </div>
                                <div>
                                    <span class="text-muted">Precio total:</span>
                                    <span>${{ cart.total_price }}.00</span>
                                </div>
                            </div>
                            {% for item in cart.items.all %}
                            <div class="card mb-3">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between">
                                        <div class="d-flex flex-row align-items-center">
                                            <div>
                                                <img src="https://www.odoo.com/web/image/res.users/1072846/image_1024?unique=3f33558" class="img-fluid rounded-3" alt="Shopping item" style="width: 65px; height: 65px;;">
                                            </div>
                                            <div class="ms-3">
                                                <h5>{{ item }}</h5>
                                                <p class="small mb-0">{{ item.product.description }}</p>
                                            </div>
                                        </div>
                                        <div class="d-flex flex-row align-items-center">
                                            <div>
                                                <form action="{% url 'shop:cart-update' item.id %}" method="post">
                                                    {% csrf_token %}
                                                    <div class="input-group">
                                                        {{ item.get_form.quantity }}
                                                        <button type="submit" class="btn btn-primary">
                                                            <i class="fas fa-sync-alt"></i>
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                            <div class="px-3">
                                                <h5 class="mb-0">${{ item.product.price }}.00</h5>
                                            </div>
                                            <a href="{% url 'shop:cart-remove' item.id %}" style="color: #cecece;"><i class="fas fa-trash-alt"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>        
                    </div>
                </div>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 text-center">
            <img src="{{ product.image.url }}" alt="Generic product" class="img-fluid">
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <span class="text-primary float-end">${{ product.price }}.00</span>
                    <h5>{{ product }}</h5>
                    <p>{{ product.description }}</p>
                    <form action="{% url 'shop:cart-add' product.id %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            {{ form.quantity }}
                            <button type="submit" class="btn btn-primary">Add to cart</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/product/form.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Crear Producto</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>
        
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-4">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <input type="submit" value="Crear" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% block content %}
<div class="container mt-5">
    <h1>Productos</h1>
    <div class="row">
        {% for product in products %}
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <span class="text-primary float-end">${{ product.price }}.00</span>
                    <h5>{{ product }}</h5>
                    <p>{{ product.description }}</p>
                    {{ product.created_at | date:"d/m/Y" }}
                    <a href="{% url 'shop:product-detail' product.id %}" class="btn btn-primary">Ver más</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}